# Generated by Django 4.2.5 on 2023-09-07 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('fam', models.CharField(blank=True, max_length=50)),
                ('otch', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField(editable=True)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=3)),
                ('summer', models.CharField(blank=True, max_length=3)),
                ('autumn', models.CharField(blank=True, max_length=3)),
                ('spring', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('other_titles', models.CharField(max_length=250)),
                ('connect', models.CharField(max_length=250)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('N', 'новый'), ('P', 'в работе'), ('A', 'принято'), ('R', 'отклонено')], default='N', max_length=1)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coordinates')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.image')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perevaladded')),
            ],
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='image',
            field=models.ManyToManyField(through='app.PerevalImage', to='app.image'),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level'),
        ),
    ]
