# Generated by Django 4.2.5 on 2023-09-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beautyTitle', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('other_titles', models.CharField(max_length=250)),
                ('connect', models.CharField(max_length=250)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('N', 'новый'), ('P', 'в работе'), ('A', 'принято'), ('R', 'отклонено')], default='N', max_length=1)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coordinates')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.image')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perevaladded')),
            ],
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='image',
            field=models.ManyToManyField(through='app.PerevalImage', to='app.image'),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level'),
        ),
    ]
