# Generated by Django 4.2.5 on 2023-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_perevaladded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevaladded',
            name='image',
            field=models.ManyToManyField(through='app.PerevalImage', to='app.image'),
        ),
    ]
