# Generated by Django 4.2.5 on 2023-09-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perevaladded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
