# Generated by Django 4.2.5 on 2023-09-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevalimage',
            old_name='image',
            new_name='data',
        ),
    ]
