# Generated by Django 4.2.5 on 2023-09-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_image_perevalimage_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='perevalimage',
            old_name='data',
            new_name='image',
        ),
    ]
