# Generated by Django 4.2.5 on 2023-09-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_image_image_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(upload_to='image/%Y/%m/%d'),
        ),
    ]
